// Code generated by protoc-gen-go. DO NOT EDIT.
// source: storage.proto

package storage

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type StorageResponse_Error int32

const (
	StorageResponse_ERROR_NONE         StorageResponse_Error = 0
	StorageResponse_ERROR_UNKNOWN      StorageResponse_Error = 1
	StorageResponse_ERROR_LACK_STORAGE StorageResponse_Error = 2
)

var StorageResponse_Error_name = map[int32]string{
	0: "ERROR_NONE",
	1: "ERROR_UNKNOWN",
	2: "ERROR_LACK_STORAGE",
}

var StorageResponse_Error_value = map[string]int32{
	"ERROR_NONE":         0,
	"ERROR_UNKNOWN":      1,
	"ERROR_LACK_STORAGE": 2,
}

func (x StorageResponse_Error) String() string {
	return proto.EnumName(StorageResponse_Error_name, int32(x))
}

func (StorageResponse_Error) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0d2c4ccf1453ffdb, []int{5, 0}
}

type DataBlock_Type int32

const (
	DataBlock_STREAM DataBlock_Type = 0
	DataBlock_URI    DataBlock_Type = 1
)

var DataBlock_Type_name = map[int32]string{
	0: "STREAM",
	1: "URI",
}

var DataBlock_Type_value = map[string]int32{
	"STREAM": 0,
	"URI":    1,
}

func (x DataBlock_Type) String() string {
	return proto.EnumName(DataBlock_Type_name, int32(x))
}

func (DataBlock_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0d2c4ccf1453ffdb, []int{7, 0}
}

type DataResponse_Encode int32

const (
	DataResponse_NONE  DataResponse_Encode = 0
	DataResponse_IMAGE DataResponse_Encode = 1
)

var DataResponse_Encode_name = map[int32]string{
	0: "NONE",
	1: "IMAGE",
}

var DataResponse_Encode_value = map[string]int32{
	"NONE":  0,
	"IMAGE": 1,
}

func (x DataResponse_Encode) String() string {
	return proto.EnumName(DataResponse_Encode_name, int32(x))
}

func (DataResponse_Encode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0d2c4ccf1453ffdb, []int{8, 0}
}

type PingRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingRequest) Reset()         { *m = PingRequest{} }
func (m *PingRequest) String() string { return proto.CompactTextString(m) }
func (*PingRequest) ProtoMessage()    {}
func (*PingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d2c4ccf1453ffdb, []int{0}
}

func (m *PingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingRequest.Unmarshal(m, b)
}
func (m *PingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingRequest.Marshal(b, m, deterministic)
}
func (m *PingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingRequest.Merge(m, src)
}
func (m *PingRequest) XXX_Size() int {
	return xxx_messageInfo_PingRequest.Size(m)
}
func (m *PingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PingRequest proto.InternalMessageInfo

type PongResponse struct {
	Version              string   `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Size                 int64    `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Block                int64    `protobuf:"varint,3,opt,name=block,proto3" json:"block,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PongResponse) Reset()         { *m = PongResponse{} }
func (m *PongResponse) String() string { return proto.CompactTextString(m) }
func (*PongResponse) ProtoMessage()    {}
func (*PongResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d2c4ccf1453ffdb, []int{1}
}

func (m *PongResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PongResponse.Unmarshal(m, b)
}
func (m *PongResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PongResponse.Marshal(b, m, deterministic)
}
func (m *PongResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PongResponse.Merge(m, src)
}
func (m *PongResponse) XXX_Size() int {
	return xxx_messageInfo_PongResponse.Size(m)
}
func (m *PongResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PongResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PongResponse proto.InternalMessageInfo

func (m *PongResponse) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *PongResponse) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *PongResponse) GetBlock() int64 {
	if m != nil {
		return m.Block
	}
	return 0
}

type StorageCreateRequest struct {
	Hash                 []byte   `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Size                 int64    `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StorageCreateRequest) Reset()         { *m = StorageCreateRequest{} }
func (m *StorageCreateRequest) String() string { return proto.CompactTextString(m) }
func (*StorageCreateRequest) ProtoMessage()    {}
func (*StorageCreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d2c4ccf1453ffdb, []int{2}
}

func (m *StorageCreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StorageCreateRequest.Unmarshal(m, b)
}
func (m *StorageCreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StorageCreateRequest.Marshal(b, m, deterministic)
}
func (m *StorageCreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StorageCreateRequest.Merge(m, src)
}
func (m *StorageCreateRequest) XXX_Size() int {
	return xxx_messageInfo_StorageCreateRequest.Size(m)
}
func (m *StorageCreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StorageCreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StorageCreateRequest proto.InternalMessageInfo

func (m *StorageCreateRequest) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *StorageCreateRequest) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *StorageCreateRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type StorageStoreRequest struct {
	Info                 []byte   `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	Index                int64    `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	Data                 []byte   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Hash                 []byte   `protobuf:"bytes,4,opt,name=hash,proto3" json:"hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StorageStoreRequest) Reset()         { *m = StorageStoreRequest{} }
func (m *StorageStoreRequest) String() string { return proto.CompactTextString(m) }
func (*StorageStoreRequest) ProtoMessage()    {}
func (*StorageStoreRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d2c4ccf1453ffdb, []int{3}
}

func (m *StorageStoreRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StorageStoreRequest.Unmarshal(m, b)
}
func (m *StorageStoreRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StorageStoreRequest.Marshal(b, m, deterministic)
}
func (m *StorageStoreRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StorageStoreRequest.Merge(m, src)
}
func (m *StorageStoreRequest) XXX_Size() int {
	return xxx_messageInfo_StorageStoreRequest.Size(m)
}
func (m *StorageStoreRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StorageStoreRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StorageStoreRequest proto.InternalMessageInfo

func (m *StorageStoreRequest) GetInfo() []byte {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *StorageStoreRequest) GetIndex() int64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *StorageStoreRequest) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *StorageStoreRequest) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

type StorageFinishRequest struct {
	Hash                 []byte   `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StorageFinishRequest) Reset()         { *m = StorageFinishRequest{} }
func (m *StorageFinishRequest) String() string { return proto.CompactTextString(m) }
func (*StorageFinishRequest) ProtoMessage()    {}
func (*StorageFinishRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d2c4ccf1453ffdb, []int{4}
}

func (m *StorageFinishRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StorageFinishRequest.Unmarshal(m, b)
}
func (m *StorageFinishRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StorageFinishRequest.Marshal(b, m, deterministic)
}
func (m *StorageFinishRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StorageFinishRequest.Merge(m, src)
}
func (m *StorageFinishRequest) XXX_Size() int {
	return xxx_messageInfo_StorageFinishRequest.Size(m)
}
func (m *StorageFinishRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StorageFinishRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StorageFinishRequest proto.InternalMessageInfo

func (m *StorageFinishRequest) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

type StorageResponse struct {
	Code                 StorageResponse_Error `protobuf:"varint,1,opt,name=code,proto3,enum=StorageResponse_Error" json:"code,omitempty"`
	Message              string                `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *StorageResponse) Reset()         { *m = StorageResponse{} }
func (m *StorageResponse) String() string { return proto.CompactTextString(m) }
func (*StorageResponse) ProtoMessage()    {}
func (*StorageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d2c4ccf1453ffdb, []int{5}
}

func (m *StorageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StorageResponse.Unmarshal(m, b)
}
func (m *StorageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StorageResponse.Marshal(b, m, deterministic)
}
func (m *StorageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StorageResponse.Merge(m, src)
}
func (m *StorageResponse) XXX_Size() int {
	return xxx_messageInfo_StorageResponse.Size(m)
}
func (m *StorageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StorageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StorageResponse proto.InternalMessageInfo

func (m *StorageResponse) GetCode() StorageResponse_Error {
	if m != nil {
		return m.Code
	}
	return StorageResponse_ERROR_NONE
}

func (m *StorageResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type GetResponse struct {
	Hash                 []byte   `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetResponse) Reset()         { *m = GetResponse{} }
func (m *GetResponse) String() string { return proto.CompactTextString(m) }
func (*GetResponse) ProtoMessage()    {}
func (*GetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d2c4ccf1453ffdb, []int{6}
}

func (m *GetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetResponse.Unmarshal(m, b)
}
func (m *GetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetResponse.Marshal(b, m, deterministic)
}
func (m *GetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetResponse.Merge(m, src)
}
func (m *GetResponse) XXX_Size() int {
	return xxx_messageInfo_GetResponse.Size(m)
}
func (m *GetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetResponse proto.InternalMessageInfo

func (m *GetResponse) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

type DataBlock struct {
	Hash                 []byte         `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Type                 DataBlock_Type `protobuf:"varint,2,opt,name=type,proto3,enum=DataBlock_Type" json:"type,omitempty"`
	Index                int64          `protobuf:"varint,3,opt,name=index,proto3" json:"index,omitempty"`
	Data                 []byte         `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *DataBlock) Reset()         { *m = DataBlock{} }
func (m *DataBlock) String() string { return proto.CompactTextString(m) }
func (*DataBlock) ProtoMessage()    {}
func (*DataBlock) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d2c4ccf1453ffdb, []int{7}
}

func (m *DataBlock) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataBlock.Unmarshal(m, b)
}
func (m *DataBlock) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataBlock.Marshal(b, m, deterministic)
}
func (m *DataBlock) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataBlock.Merge(m, src)
}
func (m *DataBlock) XXX_Size() int {
	return xxx_messageInfo_DataBlock.Size(m)
}
func (m *DataBlock) XXX_DiscardUnknown() {
	xxx_messageInfo_DataBlock.DiscardUnknown(m)
}

var xxx_messageInfo_DataBlock proto.InternalMessageInfo

func (m *DataBlock) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *DataBlock) GetType() DataBlock_Type {
	if m != nil {
		return m.Type
	}
	return DataBlock_STREAM
}

func (m *DataBlock) GetIndex() int64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *DataBlock) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type DataResponse struct {
	Hash                 []byte              `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Block                int64               `protobuf:"varint,2,opt,name=block,proto3" json:"block,omitempty"`
	Size                 int64               `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Encode               DataResponse_Encode `protobuf:"varint,5,opt,name=encode,proto3,enum=DataResponse_Encode" json:"encode,omitempty"`
	Blocks               []*DataBlock        `protobuf:"bytes,4,rep,name=blocks,proto3" json:"blocks,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *DataResponse) Reset()         { *m = DataResponse{} }
func (m *DataResponse) String() string { return proto.CompactTextString(m) }
func (*DataResponse) ProtoMessage()    {}
func (*DataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d2c4ccf1453ffdb, []int{8}
}

func (m *DataResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataResponse.Unmarshal(m, b)
}
func (m *DataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataResponse.Marshal(b, m, deterministic)
}
func (m *DataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataResponse.Merge(m, src)
}
func (m *DataResponse) XXX_Size() int {
	return xxx_messageInfo_DataResponse.Size(m)
}
func (m *DataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DataResponse proto.InternalMessageInfo

func (m *DataResponse) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *DataResponse) GetBlock() int64 {
	if m != nil {
		return m.Block
	}
	return 0
}

func (m *DataResponse) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *DataResponse) GetEncode() DataResponse_Encode {
	if m != nil {
		return m.Encode
	}
	return DataResponse_NONE
}

func (m *DataResponse) GetBlocks() []*DataBlock {
	if m != nil {
		return m.Blocks
	}
	return nil
}

func init() {
	proto.RegisterEnum("StorageResponse_Error", StorageResponse_Error_name, StorageResponse_Error_value)
	proto.RegisterEnum("DataBlock_Type", DataBlock_Type_name, DataBlock_Type_value)
	proto.RegisterEnum("DataResponse_Encode", DataResponse_Encode_name, DataResponse_Encode_value)
	proto.RegisterType((*PingRequest)(nil), "PingRequest")
	proto.RegisterType((*PongResponse)(nil), "PongResponse")
	proto.RegisterType((*StorageCreateRequest)(nil), "StorageCreateRequest")
	proto.RegisterType((*StorageStoreRequest)(nil), "StorageStoreRequest")
	proto.RegisterType((*StorageFinishRequest)(nil), "StorageFinishRequest")
	proto.RegisterType((*StorageResponse)(nil), "StorageResponse")
	proto.RegisterType((*GetResponse)(nil), "GetResponse")
	proto.RegisterType((*DataBlock)(nil), "DataBlock")
	proto.RegisterType((*DataResponse)(nil), "DataResponse")
}

func init() {
	proto.RegisterFile("storage.proto", fileDescriptor_0d2c4ccf1453ffdb)
}

var fileDescriptor_0d2c4ccf1453ffdb = []byte{
	// 540 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0xef, 0x6e, 0xd3, 0x30,
	0x10, 0xaf, 0x9b, 0x3f, 0x23, 0xd7, 0xb4, 0x0b, 0xa6, 0x4c, 0x55, 0x11, 0x52, 0x31, 0x08, 0x55,
	0x13, 0xf2, 0x87, 0xf6, 0x09, 0xba, 0x11, 0xca, 0x34, 0xd6, 0x4e, 0x6e, 0x27, 0x3e, 0x4e, 0xd9,
	0x6a, 0xda, 0x88, 0x2e, 0x2e, 0x71, 0x40, 0x8c, 0x57, 0xe0, 0x11, 0x78, 0x16, 0x9e, 0x8b, 0xaf,
	0xc8, 0x76, 0x9a, 0x66, 0x53, 0x34, 0x69, 0x9f, 0x72, 0xe7, 0xbb, 0xfb, 0xf9, 0xe7, 0xbb, 0xdf,
	0x05, 0x9a, 0x32, 0x13, 0x69, 0xb4, 0xe4, 0x74, 0x93, 0x8a, 0x4c, 0x90, 0x26, 0x34, 0xce, 0xe3,
	0x64, 0xc9, 0xf8, 0xb7, 0xef, 0x5c, 0x66, 0x84, 0x81, 0x7f, 0x2e, 0x94, 0x2b, 0x37, 0x22, 0x91,
	0x1c, 0x77, 0x60, 0xef, 0x07, 0x4f, 0x65, 0x2c, 0x92, 0x0e, 0xea, 0xa1, 0xbe, 0xc7, 0xb6, 0x2e,
	0xc6, 0x60, 0xcb, 0xf8, 0x17, 0xef, 0xd4, 0x7b, 0xa8, 0x6f, 0x31, 0x6d, 0xe3, 0x36, 0x38, 0x57,
	0x6b, 0x71, 0xfd, 0xb5, 0x63, 0xe9, 0x43, 0xe3, 0x10, 0x06, 0xed, 0x99, 0xb9, 0xf3, 0x38, 0xe5,
	0x51, 0xc6, 0xf3, 0xbb, 0x14, 0xc2, 0x2a, 0x92, 0x2b, 0x0d, 0xec, 0x33, 0x6d, 0x57, 0xa2, 0x62,
	0xb0, 0x93, 0xe8, 0x86, 0x6b, 0x50, 0x8f, 0x69, 0x9b, 0x2c, 0xe1, 0x59, 0x8e, 0xa9, 0x3e, 0x65,
	0xc8, 0x38, 0xf9, 0x22, 0xb6, 0x90, 0xca, 0x56, 0xa4, 0xe2, 0x64, 0xc1, 0x7f, 0xe6, 0x98, 0xc6,
	0x51, 0x99, 0x8b, 0x28, 0x8b, 0x34, 0xa8, 0xcf, 0xb4, 0x5d, 0x10, 0xb2, 0x77, 0x84, 0xc8, 0x61,
	0x41, 0xfe, 0x43, 0x9c, 0xc4, 0x72, 0xf5, 0x00, 0x79, 0xf2, 0x07, 0xc1, 0x7e, 0x9e, 0x5c, 0x34,
	0xf0, 0x10, 0xec, 0x6b, 0xb1, 0xe0, 0x3a, 0xaf, 0x35, 0x38, 0xa0, 0xf7, 0xe2, 0x34, 0x4c, 0x53,
	0x91, 0x32, 0x9d, 0xa3, 0x9a, 0x7d, 0xc3, 0xa5, 0x8c, 0x96, 0xe6, 0xfd, 0x1e, 0xdb, 0xba, 0xe4,
	0x08, 0x1c, 0x9d, 0x88, 0x5b, 0x00, 0x21, 0x63, 0x53, 0x76, 0x39, 0x99, 0x4e, 0xc2, 0xa0, 0x86,
	0x9f, 0x42, 0xd3, 0xf8, 0x17, 0x93, 0xd3, 0xc9, 0xf4, 0xf3, 0x24, 0x40, 0xf8, 0x00, 0xb0, 0x39,
	0xfa, 0x34, 0x3a, 0x3e, 0xbd, 0x9c, 0xcd, 0xa7, 0x6c, 0x34, 0x0e, 0x83, 0x3a, 0x79, 0x05, 0x8d,
	0x31, 0xcf, 0x0a, 0x62, 0x55, 0x0f, 0xf8, 0x8d, 0xc0, 0x7b, 0x1f, 0x65, 0xd1, 0x91, 0x9a, 0x5b,
	0xe5, 0x7c, 0x5e, 0x83, 0x9d, 0xdd, 0x6e, 0x0c, 0xbf, 0xd6, 0x60, 0x9f, 0x16, 0xd9, 0x74, 0x7e,
	0xbb, 0xe1, 0x4c, 0x07, 0x77, 0x1d, 0xb7, 0xaa, 0x3a, 0x6e, 0xef, 0x3a, 0x4e, 0x5e, 0x80, 0xad,
	0xea, 0x30, 0x80, 0x3b, 0x9b, 0xb3, 0x70, 0x74, 0x16, 0xd4, 0xf0, 0x1e, 0x58, 0x17, 0xec, 0x24,
	0x40, 0xe4, 0x2f, 0x02, 0x5f, 0xe1, 0x3f, 0x44, 0x79, 0x27, 0xb9, 0x7a, 0x49, 0x72, 0x85, 0x8c,
	0xac, 0x92, 0x8c, 0xde, 0x81, 0xcb, 0x13, 0x3d, 0x0b, 0x47, 0x93, 0x6f, 0xd3, 0x32, 0x38, 0x0d,
	0x75, 0x8c, 0xe5, 0x39, 0x98, 0x80, 0xab, 0xa1, 0x64, 0xc7, 0xee, 0x59, 0xfd, 0xc6, 0x00, 0x76,
	0x4f, 0x65, 0x79, 0x84, 0xbc, 0x04, 0xd7, 0x54, 0xe1, 0x27, 0x60, 0xe7, 0x03, 0xf1, 0xc0, 0x39,
	0x39, 0x53, 0x0d, 0x47, 0x83, 0x7f, 0x08, 0xbc, 0xb1, 0xc8, 0x07, 0x8e, 0xdf, 0x82, 0xf3, 0x91,
	0xaf, 0xd7, 0x02, 0xfb, 0xb4, 0xb4, 0x70, 0xdd, 0x26, 0x2d, 0xef, 0x1b, 0xa9, 0xe1, 0x21, 0xb8,
	0x66, 0x4d, 0xf0, 0x73, 0x5a, 0xb5, 0x36, 0xdd, 0xe0, 0xbe, 0x86, 0x48, 0x0d, 0x0f, 0xc0, 0xd1,
	0x7b, 0xf0, 0x98, 0x9a, 0x21, 0xb8, 0x46, 0xd2, 0x8f, 0x29, 0x7a, 0x03, 0xd6, 0x98, 0x67, 0xd8,
	0xa7, 0x25, 0x29, 0x75, 0x9b, 0x77, 0x3a, 0x49, 0x6a, 0x57, 0xae, 0xfe, 0xb7, 0x0c, 0xff, 0x07,
	0x00, 0x00, 0xff, 0xff, 0x8a, 0xa9, 0x0a, 0xe7, 0x6c, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// GoStorageClient is the client API for GoStorage service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GoStorageClient interface {
	// 获取状态
	Hello(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PongResponse, error)
	// 创建数据
	Create(ctx context.Context, in *StorageCreateRequest, opts ...grpc.CallOption) (*StorageResponse, error)
	// 保存数据
	Store(ctx context.Context, in *StorageCreateRequest, opts ...grpc.CallOption) (*StorageResponse, error)
	// 完成数据
	Finish(ctx context.Context, in *StorageCreateRequest, opts ...grpc.CallOption) (*StorageResponse, error)
	// 获取数据
	Get(ctx context.Context, in *GetResponse, opts ...grpc.CallOption) (*DataResponse, error)
}

type goStorageClient struct {
	cc grpc.ClientConnInterface
}

func NewGoStorageClient(cc grpc.ClientConnInterface) GoStorageClient {
	return &goStorageClient{cc}
}

func (c *goStorageClient) Hello(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PongResponse, error) {
	out := new(PongResponse)
	err := c.cc.Invoke(ctx, "/GoStorage/Hello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goStorageClient) Create(ctx context.Context, in *StorageCreateRequest, opts ...grpc.CallOption) (*StorageResponse, error) {
	out := new(StorageResponse)
	err := c.cc.Invoke(ctx, "/GoStorage/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goStorageClient) Store(ctx context.Context, in *StorageCreateRequest, opts ...grpc.CallOption) (*StorageResponse, error) {
	out := new(StorageResponse)
	err := c.cc.Invoke(ctx, "/GoStorage/Store", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goStorageClient) Finish(ctx context.Context, in *StorageCreateRequest, opts ...grpc.CallOption) (*StorageResponse, error) {
	out := new(StorageResponse)
	err := c.cc.Invoke(ctx, "/GoStorage/Finish", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goStorageClient) Get(ctx context.Context, in *GetResponse, opts ...grpc.CallOption) (*DataResponse, error) {
	out := new(DataResponse)
	err := c.cc.Invoke(ctx, "/GoStorage/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GoStorageServer is the server API for GoStorage service.
type GoStorageServer interface {
	// 获取状态
	Hello(context.Context, *PingRequest) (*PongResponse, error)
	// 创建数据
	Create(context.Context, *StorageCreateRequest) (*StorageResponse, error)
	// 保存数据
	Store(context.Context, *StorageCreateRequest) (*StorageResponse, error)
	// 完成数据
	Finish(context.Context, *StorageCreateRequest) (*StorageResponse, error)
	// 获取数据
	Get(context.Context, *GetResponse) (*DataResponse, error)
}

// UnimplementedGoStorageServer can be embedded to have forward compatible implementations.
type UnimplementedGoStorageServer struct {
}

func (*UnimplementedGoStorageServer) Hello(ctx context.Context, req *PingRequest) (*PongResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Hello not implemented")
}
func (*UnimplementedGoStorageServer) Create(ctx context.Context, req *StorageCreateRequest) (*StorageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (*UnimplementedGoStorageServer) Store(ctx context.Context, req *StorageCreateRequest) (*StorageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Store not implemented")
}
func (*UnimplementedGoStorageServer) Finish(ctx context.Context, req *StorageCreateRequest) (*StorageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Finish not implemented")
}
func (*UnimplementedGoStorageServer) Get(ctx context.Context, req *GetResponse) (*DataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}

func RegisterGoStorageServer(s *grpc.Server, srv GoStorageServer) {
	s.RegisterService(&_GoStorage_serviceDesc, srv)
}

func _GoStorage_Hello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoStorageServer).Hello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/GoStorage/Hello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoStorageServer).Hello(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoStorage_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StorageCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoStorageServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/GoStorage/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoStorageServer).Create(ctx, req.(*StorageCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoStorage_Store_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StorageCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoStorageServer).Store(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/GoStorage/Store",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoStorageServer).Store(ctx, req.(*StorageCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoStorage_Finish_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StorageCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoStorageServer).Finish(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/GoStorage/Finish",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoStorageServer).Finish(ctx, req.(*StorageCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoStorage_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetResponse)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoStorageServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/GoStorage/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoStorageServer).Get(ctx, req.(*GetResponse))
	}
	return interceptor(ctx, in, info, handler)
}

var _GoStorage_serviceDesc = grpc.ServiceDesc{
	ServiceName: "GoStorage",
	HandlerType: (*GoStorageServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Hello",
			Handler:    _GoStorage_Hello_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _GoStorage_Create_Handler,
		},
		{
			MethodName: "Store",
			Handler:    _GoStorage_Store_Handler,
		},
		{
			MethodName: "Finish",
			Handler:    _GoStorage_Finish_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _GoStorage_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "storage.proto",
}
