// Code generated by protoc-gen-go. DO NOT EDIT.
// source: storage.proto

package storage

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type StorageResponse_Error int32

const (
	StorageResponse_ERROR_NONE         StorageResponse_Error = 0
	StorageResponse_ERROR_UNKNOWN      StorageResponse_Error = 1
	StorageResponse_ERROR_LACK_STORAGE StorageResponse_Error = 2
)

var StorageResponse_Error_name = map[int32]string{
	0: "ERROR_NONE",
	1: "ERROR_UNKNOWN",
	2: "ERROR_LACK_STORAGE",
}

var StorageResponse_Error_value = map[string]int32{
	"ERROR_NONE":         0,
	"ERROR_UNKNOWN":      1,
	"ERROR_LACK_STORAGE": 2,
}

func (x StorageResponse_Error) String() string {
	return proto.EnumName(StorageResponse_Error_name, int32(x))
}

func (StorageResponse_Error) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0d2c4ccf1453ffdb, []int{4, 0}
}

type DataBlock_Type int32

const (
	DataBlock_STREAM DataBlock_Type = 0
	DataBlock_URI    DataBlock_Type = 1
)

var DataBlock_Type_name = map[int32]string{
	0: "STREAM",
	1: "URI",
}

var DataBlock_Type_value = map[string]int32{
	"STREAM": 0,
	"URI":    1,
}

func (x DataBlock_Type) String() string {
	return proto.EnumName(DataBlock_Type_name, int32(x))
}

func (DataBlock_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0d2c4ccf1453ffdb, []int{6, 0}
}

type DataBlock_Encode int32

const (
	DataBlock_NONE  DataBlock_Encode = 0
	DataBlock_IMAGE DataBlock_Encode = 1
)

var DataBlock_Encode_name = map[int32]string{
	0: "NONE",
	1: "IMAGE",
}

var DataBlock_Encode_value = map[string]int32{
	"NONE":  0,
	"IMAGE": 1,
}

func (x DataBlock_Encode) String() string {
	return proto.EnumName(DataBlock_Encode_name, int32(x))
}

func (DataBlock_Encode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0d2c4ccf1453ffdb, []int{6, 1}
}

type HelloRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloRequest) Reset()         { *m = HelloRequest{} }
func (m *HelloRequest) String() string { return proto.CompactTextString(m) }
func (*HelloRequest) ProtoMessage()    {}
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d2c4ccf1453ffdb, []int{0}
}

func (m *HelloRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloRequest.Unmarshal(m, b)
}
func (m *HelloRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloRequest.Marshal(b, m, deterministic)
}
func (m *HelloRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloRequest.Merge(m, src)
}
func (m *HelloRequest) XXX_Size() int {
	return xxx_messageInfo_HelloRequest.Size(m)
}
func (m *HelloRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HelloRequest proto.InternalMessageInfo

type StatusResponse struct {
	Version              string   `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Size                 uint64   `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Block                uint64   `protobuf:"varint,3,opt,name=block,proto3" json:"block,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatusResponse) Reset()         { *m = StatusResponse{} }
func (m *StatusResponse) String() string { return proto.CompactTextString(m) }
func (*StatusResponse) ProtoMessage()    {}
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d2c4ccf1453ffdb, []int{1}
}

func (m *StatusResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusResponse.Unmarshal(m, b)
}
func (m *StatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusResponse.Marshal(b, m, deterministic)
}
func (m *StatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusResponse.Merge(m, src)
}
func (m *StatusResponse) XXX_Size() int {
	return xxx_messageInfo_StatusResponse.Size(m)
}
func (m *StatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StatusResponse proto.InternalMessageInfo

func (m *StatusResponse) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *StatusResponse) GetSize() uint64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *StatusResponse) GetBlock() uint64 {
	if m != nil {
		return m.Block
	}
	return 0
}

type ContentRange struct {
	Start                uint64   `protobuf:"varint,1,opt,name=start,proto3" json:"start,omitempty"`
	End                  uint64   `protobuf:"varint,2,opt,name=end,proto3" json:"end,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ContentRange) Reset()         { *m = ContentRange{} }
func (m *ContentRange) String() string { return proto.CompactTextString(m) }
func (*ContentRange) ProtoMessage()    {}
func (*ContentRange) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d2c4ccf1453ffdb, []int{2}
}

func (m *ContentRange) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContentRange.Unmarshal(m, b)
}
func (m *ContentRange) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContentRange.Marshal(b, m, deterministic)
}
func (m *ContentRange) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContentRange.Merge(m, src)
}
func (m *ContentRange) XXX_Size() int {
	return xxx_messageInfo_ContentRange.Size(m)
}
func (m *ContentRange) XXX_DiscardUnknown() {
	xxx_messageInfo_ContentRange.DiscardUnknown(m)
}

var xxx_messageInfo_ContentRange proto.InternalMessageInfo

func (m *ContentRange) GetStart() uint64 {
	if m != nil {
		return m.Start
	}
	return 0
}

func (m *ContentRange) GetEnd() uint64 {
	if m != nil {
		return m.End
	}
	return 0
}

type StorageRequest struct {
	Hash                 []byte        `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	DataHash             []byte        `protobuf:"bytes,2,opt,name=dataHash,proto3" json:"dataHash,omitempty"`
	Data                 []byte        `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Size                 uint64        `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	Range                *ContentRange `protobuf:"bytes,5,opt,name=range,proto3" json:"range,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *StorageRequest) Reset()         { *m = StorageRequest{} }
func (m *StorageRequest) String() string { return proto.CompactTextString(m) }
func (*StorageRequest) ProtoMessage()    {}
func (*StorageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d2c4ccf1453ffdb, []int{3}
}

func (m *StorageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StorageRequest.Unmarshal(m, b)
}
func (m *StorageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StorageRequest.Marshal(b, m, deterministic)
}
func (m *StorageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StorageRequest.Merge(m, src)
}
func (m *StorageRequest) XXX_Size() int {
	return xxx_messageInfo_StorageRequest.Size(m)
}
func (m *StorageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StorageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StorageRequest proto.InternalMessageInfo

func (m *StorageRequest) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *StorageRequest) GetDataHash() []byte {
	if m != nil {
		return m.DataHash
	}
	return nil
}

func (m *StorageRequest) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *StorageRequest) GetSize() uint64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *StorageRequest) GetRange() *ContentRange {
	if m != nil {
		return m.Range
	}
	return nil
}

type StorageResponse struct {
	Code                 StorageResponse_Error `protobuf:"varint,1,opt,name=code,proto3,enum=StorageResponse_Error" json:"code,omitempty"`
	Message              string                `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *StorageResponse) Reset()         { *m = StorageResponse{} }
func (m *StorageResponse) String() string { return proto.CompactTextString(m) }
func (*StorageResponse) ProtoMessage()    {}
func (*StorageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d2c4ccf1453ffdb, []int{4}
}

func (m *StorageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StorageResponse.Unmarshal(m, b)
}
func (m *StorageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StorageResponse.Marshal(b, m, deterministic)
}
func (m *StorageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StorageResponse.Merge(m, src)
}
func (m *StorageResponse) XXX_Size() int {
	return xxx_messageInfo_StorageResponse.Size(m)
}
func (m *StorageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StorageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StorageResponse proto.InternalMessageInfo

func (m *StorageResponse) GetCode() StorageResponse_Error {
	if m != nil {
		return m.Code
	}
	return StorageResponse_ERROR_NONE
}

func (m *StorageResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type GetResponse struct {
	Hash                 []byte   `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetResponse) Reset()         { *m = GetResponse{} }
func (m *GetResponse) String() string { return proto.CompactTextString(m) }
func (*GetResponse) ProtoMessage()    {}
func (*GetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d2c4ccf1453ffdb, []int{5}
}

func (m *GetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetResponse.Unmarshal(m, b)
}
func (m *GetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetResponse.Marshal(b, m, deterministic)
}
func (m *GetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetResponse.Merge(m, src)
}
func (m *GetResponse) XXX_Size() int {
	return xxx_messageInfo_GetResponse.Size(m)
}
func (m *GetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetResponse proto.InternalMessageInfo

func (m *GetResponse) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

type DataBlock struct {
	Hash                 []byte           `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Type                 DataBlock_Type   `protobuf:"varint,2,opt,name=type,proto3,enum=DataBlock_Type" json:"type,omitempty"`
	Range                *ContentRange    `protobuf:"bytes,3,opt,name=range,proto3" json:"range,omitempty"`
	Data                 []byte           `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	Encode               DataBlock_Encode `protobuf:"varint,5,opt,name=encode,proto3,enum=DataBlock_Encode" json:"encode,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *DataBlock) Reset()         { *m = DataBlock{} }
func (m *DataBlock) String() string { return proto.CompactTextString(m) }
func (*DataBlock) ProtoMessage()    {}
func (*DataBlock) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d2c4ccf1453ffdb, []int{6}
}

func (m *DataBlock) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataBlock.Unmarshal(m, b)
}
func (m *DataBlock) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataBlock.Marshal(b, m, deterministic)
}
func (m *DataBlock) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataBlock.Merge(m, src)
}
func (m *DataBlock) XXX_Size() int {
	return xxx_messageInfo_DataBlock.Size(m)
}
func (m *DataBlock) XXX_DiscardUnknown() {
	xxx_messageInfo_DataBlock.DiscardUnknown(m)
}

var xxx_messageInfo_DataBlock proto.InternalMessageInfo

func (m *DataBlock) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *DataBlock) GetType() DataBlock_Type {
	if m != nil {
		return m.Type
	}
	return DataBlock_STREAM
}

func (m *DataBlock) GetRange() *ContentRange {
	if m != nil {
		return m.Range
	}
	return nil
}

func (m *DataBlock) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *DataBlock) GetEncode() DataBlock_Encode {
	if m != nil {
		return m.Encode
	}
	return DataBlock_NONE
}

type DataResponse struct {
	Hash                 []byte       `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Blocks               []*DataBlock `protobuf:"bytes,2,rep,name=blocks,proto3" json:"blocks,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *DataResponse) Reset()         { *m = DataResponse{} }
func (m *DataResponse) String() string { return proto.CompactTextString(m) }
func (*DataResponse) ProtoMessage()    {}
func (*DataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d2c4ccf1453ffdb, []int{7}
}

func (m *DataResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataResponse.Unmarshal(m, b)
}
func (m *DataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataResponse.Marshal(b, m, deterministic)
}
func (m *DataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataResponse.Merge(m, src)
}
func (m *DataResponse) XXX_Size() int {
	return xxx_messageInfo_DataResponse.Size(m)
}
func (m *DataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DataResponse proto.InternalMessageInfo

func (m *DataResponse) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *DataResponse) GetBlocks() []*DataBlock {
	if m != nil {
		return m.Blocks
	}
	return nil
}

func init() {
	proto.RegisterEnum("StorageResponse_Error", StorageResponse_Error_name, StorageResponse_Error_value)
	proto.RegisterEnum("DataBlock_Type", DataBlock_Type_name, DataBlock_Type_value)
	proto.RegisterEnum("DataBlock_Encode", DataBlock_Encode_name, DataBlock_Encode_value)
	proto.RegisterType((*HelloRequest)(nil), "HelloRequest")
	proto.RegisterType((*StatusResponse)(nil), "StatusResponse")
	proto.RegisterType((*ContentRange)(nil), "ContentRange")
	proto.RegisterType((*StorageRequest)(nil), "StorageRequest")
	proto.RegisterType((*StorageResponse)(nil), "StorageResponse")
	proto.RegisterType((*GetResponse)(nil), "GetResponse")
	proto.RegisterType((*DataBlock)(nil), "DataBlock")
	proto.RegisterType((*DataResponse)(nil), "DataResponse")
}

func init() {
	proto.RegisterFile("storage.proto", fileDescriptor_0d2c4ccf1453ffdb)
}

var fileDescriptor_0d2c4ccf1453ffdb = []byte{
	// 512 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x93, 0xdd, 0x4e, 0xdb, 0x30,
	0x14, 0xc7, 0xeb, 0x26, 0x29, 0xf4, 0xf4, 0x2b, 0x58, 0x13, 0x8a, 0x98, 0x26, 0x75, 0xe6, 0x62,
	0x65, 0x17, 0xb9, 0xe8, 0xa4, 0xdd, 0x17, 0x96, 0x15, 0xc4, 0x68, 0xa5, 0xd3, 0xa2, 0x5d, 0x22,
	0x43, 0xad, 0x82, 0xd6, 0xc5, 0x5d, 0x6c, 0x90, 0xd8, 0x2b, 0x4c, 0x7b, 0x82, 0xbd, 0xde, 0x1e,
	0x64, 0xf2, 0x49, 0x08, 0x61, 0xeb, 0xb8, 0x3b, 0x1f, 0xff, 0x1c, 0xff, 0xf3, 0xb3, 0x0f, 0x74,
	0x8c, 0xd5, 0x99, 0x5c, 0xaa, 0x78, 0x9d, 0x69, 0xab, 0x45, 0x17, 0xda, 0xc7, 0x6a, 0xb5, 0xd2,
	0xa8, 0xbe, 0xdd, 0x2a, 0x63, 0xc5, 0x1c, 0xba, 0x33, 0x2b, 0xed, 0xad, 0x41, 0x65, 0xd6, 0x3a,
	0x35, 0x8a, 0x47, 0xb0, 0x75, 0xa7, 0x32, 0x73, 0xa3, 0xd3, 0x88, 0xf5, 0xd9, 0xa0, 0x89, 0x0f,
	0x29, 0xe7, 0xe0, 0x9b, 0x9b, 0xef, 0x2a, 0xaa, 0xf7, 0xd9, 0xc0, 0x47, 0x8a, 0xf9, 0x0b, 0x08,
	0x2e, 0x57, 0xfa, 0xea, 0x4b, 0xe4, 0x51, 0x31, 0x4f, 0xc4, 0x7b, 0x68, 0x1f, 0xe9, 0xd4, 0xaa,
	0xd4, 0xa2, 0x4c, 0x97, 0xa4, 0x32, 0x56, 0x66, 0x96, 0x26, 0xfa, 0x98, 0x27, 0x3c, 0x04, 0x4f,
	0xa5, 0x8b, 0x62, 0x9c, 0x0b, 0xc5, 0x4f, 0xe6, 0xec, 0x90, 0xdf, 0xc2, 0xa0, 0x3b, 0xf4, 0x5a,
	0x9a, 0x6b, 0xfa, 0xb2, 0x8d, 0x14, 0xf3, 0x3d, 0xd8, 0x5e, 0x48, 0x2b, 0x8f, 0x5d, 0xbd, 0x4e,
	0xf5, 0x32, 0x77, 0x7a, 0x17, 0x93, 0x9f, 0x36, 0x52, 0x5c, 0x1a, 0xf7, 0x2b, 0xc6, 0xf7, 0x21,
	0xc8, 0x9c, 0xb7, 0x28, 0xe8, 0xb3, 0x41, 0x6b, 0xd8, 0x89, 0xab, 0x86, 0x31, 0xef, 0x89, 0x5f,
	0x0c, 0x7a, 0xa5, 0x9f, 0x82, 0xcf, 0x5b, 0xf0, 0xaf, 0xf4, 0x42, 0x91, 0xa1, 0xee, 0x70, 0x37,
	0xfe, 0xab, 0x1f, 0x27, 0x59, 0xa6, 0x33, 0x24, 0x8d, 0x63, 0xf9, 0x55, 0x19, 0x23, 0x97, 0x39,
	0xb4, 0x26, 0x3e, 0xa4, 0xe2, 0x10, 0x02, 0x12, 0xf2, 0x2e, 0x40, 0x82, 0x38, 0xc5, 0x8b, 0xc9,
	0x74, 0x92, 0x84, 0x35, 0xbe, 0x03, 0x9d, 0x3c, 0x3f, 0x9f, 0x9c, 0x4e, 0xa6, 0x9f, 0x27, 0x21,
	0xe3, 0xbb, 0xc0, 0xf3, 0xd2, 0xa7, 0xd1, 0xd1, 0xe9, 0xc5, 0x6c, 0x3e, 0xc5, 0xd1, 0x38, 0x09,
	0xeb, 0xe2, 0x35, 0xb4, 0xc6, 0xca, 0x96, 0xc6, 0x36, 0x90, 0x12, 0xbf, 0x19, 0x34, 0x3f, 0x48,
	0x2b, 0x0f, 0xdd, 0xb5, 0x6c, 0x64, 0xb9, 0x0f, 0xbe, 0xbd, 0x5f, 0xe7, 0xfe, 0xba, 0xc3, 0x5e,
	0x5c, 0xaa, 0xe3, 0xf9, 0xfd, 0x5a, 0x21, 0x35, 0x1f, 0x61, 0x79, 0xff, 0x87, 0x55, 0x92, 0xf7,
	0x2b, 0xe4, 0x0f, 0xa0, 0xa1, 0x52, 0xc2, 0x15, 0xd0, 0xfc, 0x9d, 0xca, 0xfc, 0x84, 0x1a, 0x58,
	0x08, 0xc4, 0x4b, 0xf0, 0xdd, 0x89, 0x1c, 0xa0, 0x31, 0x9b, 0x63, 0x32, 0x3a, 0x0b, 0x6b, 0x7c,
	0x0b, 0xbc, 0x73, 0x3c, 0x09, 0x99, 0x78, 0x05, 0x8d, 0x5c, 0xce, 0xb7, 0xc1, 0x2f, 0x48, 0x35,
	0x21, 0x38, 0x39, 0x73, 0x24, 0x98, 0xf8, 0x08, 0x6d, 0x37, 0xf7, 0x39, 0x14, 0x5c, 0x40, 0x83,
	0x1e, 0xa7, 0x89, 0xea, 0x7d, 0x6f, 0xd0, 0x1a, 0xc2, 0xa3, 0x15, 0x2c, 0x3a, 0xc3, 0x1f, 0x0c,
	0x9a, 0x63, 0x5d, 0xdc, 0x28, 0x3f, 0x80, 0x80, 0x76, 0x85, 0x77, 0xe2, 0xea, 0xce, 0xec, 0xf5,
	0xe2, 0xa7, 0x2b, 0x23, 0x6a, 0xee, 0x51, 0xcc, 0xe4, 0x9d, 0xe2, 0xbd, 0xf8, 0xe9, 0xf3, 0xdd,
	0xa4, 0x7d, 0x03, 0xde, 0x58, 0xd9, 0x7f, 0xa5, 0x9d, 0xb8, 0xfa, 0x0f, 0xa2, 0x76, 0xd9, 0xa0,
	0x95, 0x7d, 0xf7, 0x27, 0x00, 0x00, 0xff, 0xff, 0x82, 0x01, 0xe1, 0x2d, 0xc3, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// GoStorageClient is the client API for GoStorage service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GoStorageClient interface {
	// 获取状态
	Hello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	// 保存数据
	Save(ctx context.Context, in *StorageRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	// 获取数据
	Get(ctx context.Context, in *StorageRequest, opts ...grpc.CallOption) (*DataResponse, error)
}

type goStorageClient struct {
	cc grpc.ClientConnInterface
}

func NewGoStorageClient(cc grpc.ClientConnInterface) GoStorageClient {
	return &goStorageClient{cc}
}

func (c *goStorageClient) Hello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, "/GoStorage/Hello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goStorageClient) Save(ctx context.Context, in *StorageRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, "/GoStorage/Save", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goStorageClient) Get(ctx context.Context, in *StorageRequest, opts ...grpc.CallOption) (*DataResponse, error) {
	out := new(DataResponse)
	err := c.cc.Invoke(ctx, "/GoStorage/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GoStorageServer is the server API for GoStorage service.
type GoStorageServer interface {
	// 获取状态
	Hello(context.Context, *HelloRequest) (*StatusResponse, error)
	// 保存数据
	Save(context.Context, *StorageRequest) (*StatusResponse, error)
	// 获取数据
	Get(context.Context, *StorageRequest) (*DataResponse, error)
}

// UnimplementedGoStorageServer can be embedded to have forward compatible implementations.
type UnimplementedGoStorageServer struct {
}

func (*UnimplementedGoStorageServer) Hello(ctx context.Context, req *HelloRequest) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Hello not implemented")
}
func (*UnimplementedGoStorageServer) Save(ctx context.Context, req *StorageRequest) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Save not implemented")
}
func (*UnimplementedGoStorageServer) Get(ctx context.Context, req *StorageRequest) (*DataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}

func RegisterGoStorageServer(s *grpc.Server, srv GoStorageServer) {
	s.RegisterService(&_GoStorage_serviceDesc, srv)
}

func _GoStorage_Hello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoStorageServer).Hello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/GoStorage/Hello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoStorageServer).Hello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoStorage_Save_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StorageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoStorageServer).Save(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/GoStorage/Save",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoStorageServer).Save(ctx, req.(*StorageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoStorage_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StorageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoStorageServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/GoStorage/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoStorageServer).Get(ctx, req.(*StorageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _GoStorage_serviceDesc = grpc.ServiceDesc{
	ServiceName: "GoStorage",
	HandlerType: (*GoStorageServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Hello",
			Handler:    _GoStorage_Hello_Handler,
		},
		{
			MethodName: "Save",
			Handler:    _GoStorage_Save_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _GoStorage_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "storage.proto",
}
